#!/usr/bin/env bash
# reset_to_baseline.sh
#
# Purpose: from a clean git status, remove ALL Phase 1~8 deliverables and
# runtime trash, then reset harness state so that the 8 phase workflow JS
# files can be re-run from a true baseline.
#
# Use case: verify harness-methodology health end-to-end by re-running the
# full 8-phase workflow stack against the current workflow JS + harness
# submodule pin. Stress probe — failures are recorded as harness bugs and
# fixed in the submodule.
#
# Usage:
#   # In an integration-test working tree:
#   git status                    # MUST be clean (use `git stash` first)
#   bash scripts/reset_to_baseline.sh
#   python3 harness_cli.py init-project --project . --overwrite
#   # then run 8 phase workflows via Claude /workflow phaseN-...
#
# What it removes (Phase 1~8 deliverables + state + runtime trash):
#   - Phase 1: 01-requirements/, Phase1_STAGE_PASS.md
#   - Phase 2: 02-architecture/, Phase2_STAGE_PASS.md
#   - Phase 3: 03-development/, Phase3_STAGE_PASS.md
#   - Phase 4: 04-testing/, Phase4_STAGE_PASS.md, gate3_result.json
#   - Phase 5: 05-verification/, Phase5_STAGE_PASS.md, crg_baseline_p4.json
#   - Phase 6: 06-quality/, Phase6_STAGE_PASS.md, gate4_result.json,
#              crg_baseline_p6.json, bug_hunt_report.json,
#              bug_hunt_targets.json, gap_report.json
#   - Phase 7: 07-risk/, Phase7_STAGE_PASS.md, RISK_REGISTER.md,
#              RISK_MITIGATION_PLANS.md, RISK_STATUS_REPORT.md
#   - Phase 8: 08-config/CONFIG_RECORDS.md, 08-config/RELEASE_CHECKLIST.md,
#              Phase8_STAGE_PASS.md, FINAL_SIGN_OFF.md, RELEASE_NOTES.md
#   - All .methodology/agent_b_approvals/*.json
#   - All .methodology/decision_logs/
#   - All phase gate/process artifacts (gate1_result, gate2_result,
#     gate_timestamps, gap_report, quality_manifest, fr_progress,
#     sessions_spawn.log, .gate1_scores.json, effort_metrics.db,
#     improvement-proposal-2026-06-27.md)
#   - State: .methodology/state.json
#   - Trace: .harness/traces/agent_trajectory.jsonl
#   - Runtime trash:
#       .sessi-work/  .benchmarks/  .coverage
#       .mypy_cache/  .pytest_cache/  .ruff_cache/
#       coverage.json  aa03.py  r.sh
#       _*.py  _*.sh  (root-level debug/cov/runner scripts from E2E rounds)
#
# What it KEEPS (harness config + workflow JS + audit reference):
#   - .claude/workflows/*.js (8 phase workflow JS — the test subject)
#   - harness/ submodule + harness_cli.py + setup.cfg + .gitignore + .gitmodules
#   - CLAUDE.md + HANDOVER.md (HANDOVER will be regenerated by advance-phase)
#   - .methodology/SAB.json
#   - .methodology/phase{1..9}_plan.md  (reference for new runs)
#   - .methodology/plan_status.md
#   - .methodology/audit/workflow_audit_2026-06-26.md
#   - .methodology/workflow-playbook.md
#   - .methodology/trace/attestation.json
#   - .venv/  .taskq/  .code-review-graph/  .secrets.baseline
#     (toolchain runtime caches, not phase deliverables)
#   - 00-summary/ (will be empty after cleanup)

set -euo pipefail

removed=0
log_remove() {
  for path in "$@"; do
    if [ -e "$path" ]; then
      rm -rf "$path"
      echo "  removed: $path"
      removed=$((removed + 1))
    fi
  done
}

echo "============================================================"
echo " reset_to_baseline.sh — Phase 1~8 artifact removal"
echo "============================================================"

echo ""
echo "[Phase 1] deliverables"
log_remove 01-requirements/
log_remove 00-summary/Phase1_STAGE_PASS.md

echo ""
echo "[Phase 2] deliverables"
log_remove 02-architecture/
log_remove 00-summary/Phase2_STAGE_PASS.md

echo ""
echo "[Phase 3] deliverables"
log_remove 03-development/
log_remove 00-summary/Phase3_STAGE_PASS.md

echo ""
echo "[Phase 4] deliverables + gate3 artifact"
log_remove 04-testing/
log_remove 00-summary/Phase4_STAGE_PASS.md
log_remove .methodology/gate3_result.json

echo ""
echo "[Phase 5] deliverables + CRG p4 baseline"
log_remove 05-verification/
log_remove 00-summary/Phase5_STAGE_PASS.md
log_remove .methodology/crg_baseline_p4.json

echo ""
echo "[Phase 6] deliverables + gate4 + bug hunt + gap report + CRG p6"
log_remove 06-quality/
log_remove 00-summary/Phase6_STAGE_PASS.md
log_remove .methodology/gate4_result.json
log_remove .methodology/crg_baseline_p6.json
log_remove .methodology/bug_hunt_report.json
log_remove .methodology/bug_hunt_targets.json

echo ""
echo "[Phase 7] deliverables + risk artifacts"
log_remove 07-risk/
log_remove 00-summary/Phase7_STAGE_PASS.md
log_remove 08-config/RISK_REGISTER.md
log_remove 08-config/RISK_MITIGATION_PLANS.md
log_remove 08-config/RISK_STATUS_REPORT.md

echo ""
echo "[Phase 8] deliverables + sign-off"
log_remove 08-config/CONFIG_RECORDS.md
log_remove 08-config/RELEASE_CHECKLIST.md
log_remove 00-summary/Phase8_STAGE_PASS.md
log_remove FINAL_SIGN_OFF.md
log_remove RELEASE_NOTES.md

echo ""
echo "[Agent B approvals] (Phase 1~8 deliverable review records)"
log_remove .methodology/agent_b_approvals/

echo ""
echo "[Methodology] gate / process artifacts"
log_remove .methodology/decision_logs/
log_remove .methodology/fr_progress.json
log_remove .methodology/gate1_result.json
log_remove .methodology/gate2_result.json
log_remove .methodology/gate_timestamps.jsonl
log_remove .methodology/gap_report.json
log_remove .methodology/quality_manifest.json
log_remove .methodology/sessions_spawn.log
log_remove .methodology/sessions_spawn.log.lock
log_remove .methodology/.gate1_scores.json
log_remove .methodology/effort_metrics.db
log_remove .methodology/improvement-proposal-2026-06-27.md

echo ""
echo "[State + trace] reset"
log_remove .methodology/state.json
log_remove .harness/traces/agent_trajectory.jsonl

echo ""
echo "[Runtime trash] sandbox + toolchain caches + root orphan scripts"
log_remove .sessi-work/
log_remove .benchmarks/
log_remove .coverage
log_remove .coverage.cmb
log_remove .mypy_cache/
log_remove .pytest_cache/
log_remove .ruff_cache/
log_remove coverage.json
log_remove aa03.py
log_remove r.sh
# Catch-all for any root-level _*.py / _*.sh left over from E2E rounds.
# Note: this is destructive to anything matching the pattern — none of
# these are tracked per `git ls-files | grep '^_';` would show, but if
# you have a NEW file matching the pattern that should survive, rename
# it before running reset.
for f in _*.py _*.sh; do
  if [ -e "$f" ]; then
    log_remove "$f"
  fi
done

echo ""
echo "============================================================"
echo " Cleanup complete: $removed paths removed"
echo "============================================================"
echo ""
echo "Next steps to re-run the 8 phase workflow JS:"
echo "  1. python3 harness_cli.py init-project --project . --overwrite"
echo "  2. claude /workflow phase1-requirements"
echo "  3. ... advance through phase8-config"
echo ""
echo "Workflow JS is the verification subject — DO NOT modify it."
echo "If a workflow JS fails, the bug is in harness-methodology,"
echo "not in your project. Report root cause + fix in harness submodule."